<?php

/**
 * @file
 * Contains node_json_data.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function node_json_data_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the node_json_data module.
    case 'help.page.node_json_data':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A custom module for api key submission') . '</p>';
      return $output;

    default:
  }
}
